// <auto-generated />
using System;
using ExemploEntityFrameworkWebApi.src.models.contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExemploEntityFrameworkWebApi.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240725180601_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ExemploEntityFrameworkWebApi.src.models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_created_at");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_edited_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_zip_code");

                    b.Property<int>("id_person")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_person");

                    b.ToTable("address");
                });

            modelBuilder.Entity("ExemploEntityFrameworkWebApi.src.models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_description");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_edited_at");

                    b.HasKey("Id");

                    b.ToTable("gender");
                });

            modelBuilder.Entity("ExemploEntityFrameworkWebApi.src.models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dt_birth");

                    b.Property<string>("Document")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_document");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_edited_at");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_first_name");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_last_name");

                    b.Property<int?>("id_gender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_gender");

                    b.ToTable("person");
                });

            modelBuilder.Entity("ExemploEntityFrameworkWebApi.src.models.Address", b =>
                {
                    b.HasOne("ExemploEntityFrameworkWebApi.src.models.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("id_person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ExemploEntityFrameworkWebApi.src.models.Person", b =>
                {
                    b.HasOne("ExemploEntityFrameworkWebApi.src.models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("id_gender");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ExemploEntityFrameworkWebApi.src.models.Person", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
