--para firebird
CREATE TABLE usuario (
	id integer generated by default as identity primary KEY,
	nome varchar(50),
	nascimento TIMESTAMP
);

SELECT * FROM usuario ORDER BY id;
DELETE FROM usuario;
INSERT INTO usuario (id, nome, nascimento) VALUES (1, 'alex', cast ('12' || '-June-' || '1959' as date));



--para postrges
create table usuario (
	id serial primary key,
	nome varchar(50),
	nascimento timestamp
);

drop table usuario; 

insert into usuario (nome, nascimento) values ('alex', CURRENT_DATE);

select * from usuario;
